name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  mysql-variation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql:
          - builtin
          - mysql:8.1
          - mariadb:11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Shopwell
        uses: ./.
        with:
          mysql-version: ${{ matrix.mysql }}
          install: 'true'
          path: 'sw-test'
          allow-insecure-versions: 'true'

  only-storefront:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Shopwell
        uses: ./.
        with:
          install: 'true'
          install-storefront: 'true'
          path: 'sw-test'
          allow-insecure-versions: 'true'

  only-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Shopwell
        uses: ./.
        with:
          install: 'true'
          install-admin: 'true'
          path: 'sw-test'
          allow-insecure-versions: 'true'

  version-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'trunk'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Shopwell
        uses: ./.
        with:
          shopwell-version: '${{ matrix.version }}'
          path: 'sw-test'
          install: 'true'
          allow-insecure-versions: 'true'
      - name: Show version
        working-directory: sw-test
        run: ./bin/console --version

  disable-bundles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Shopwell
        uses: ./.
        with:
          install: 'true'
          path: 'sw-test'
          allow-insecure-versions: 'true'
          disable-bundles: 'Administration, Storefront, Elasticsearch'
      - name: Verify bundles are disabled
        working-directory: sw-test
        run: |
          ! grep -q 'Shopwell\\Administration' config/bundles.php
          ! grep -q 'Shopwell\\Storefront' config/bundles.php
          ! grep -q 'Shopwell\\Elasticsearch' config/bundles.php
          [ ! -d "src/Administration" ]
          [ ! -d "src/Storefront" ]
          [ ! -d "src/Elasticsearch" ]
          [ ! -d "tests/integration/Administration" ]
          [ ! -d "tests/integration/Storefront" ]
          [ ! -d "tests/integration/Elasticsearch" ]
